/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cismet.belis.gui.widget.detailWidgetPanels;

import org.jdesktop.beansbinding.BindingGroup;

import java.awt.Component;

import java.util.Collection;
import java.util.HashSet;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;

import de.cismet.belis.broker.BelisBroker;
import de.cismet.belis.broker.CidsBroker;

import de.cismet.belisEE.exception.ActionNotSuccessfulException;

import de.cismet.cids.custom.beans.belis.LeitungCustomBean;
import de.cismet.cids.custom.beans.belis.LeitungstypCustomBean;
import de.cismet.cids.custom.beans.belis.MaterialLeitungCustomBean;
import de.cismet.cids.custom.beans.belis.QuerschnittCustomBean;

/**
 * DOCUMENT ME!
 *
 * @author   Gilles Baatz
 * @version  $Revision$, $Date$
 */
public final class LeitungPanel extends AbstractDetailWidgetPanel<LeitungCustomBean> {

    //~ Static fields/initializers ---------------------------------------------

    private static final org.apache.log4j.Logger LOG = org.apache.log4j.Logger.getLogger(LeitungPanel.class);

    private static LeitungPanel instance = null;

    //~ Instance fields --------------------------------------------------------

    private Collection<LeitungstypCustomBean> leitungstypen = new HashSet<LeitungstypCustomBean>();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxLeitungLeitungstyp;
    private javax.swing.JComboBox cbxLeitungMaterial;
    private javax.swing.JComboBox cbxLeitungQuerschnitt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblLeitungLeitungstyp;
    private javax.swing.JLabel lblLeitungMaterial;
    private javax.swing.JLabel lblLeitungQuerschnitt;
    private javax.swing.JSeparator sprLeitung;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form LeitungPanel.
     */
    private LeitungPanel() {
        initComponents();
        initComponentToLabelMap();
        initPanel();

        // ToDo ugly workaround
        if ((leitungstypen != null) && (leitungstypen.size() > 0)) {
            for (final LeitungstypCustomBean curLeitungstyp : leitungstypen) {
                if (curLeitungstyp.getId().equals(1L)) {
                    BelisBroker.getInstance().setLastLeitungstyp(curLeitungstyp);
                }
            }
        }
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public static LeitungPanel getInstance() {
        if (instance == null) {
            synchronized (LeitungPanel.class) {
                if (instance == null) {
                    instance = new LeitungPanel();
                }
            }
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblLeitungMaterial = new javax.swing.JLabel();
        lblLeitungLeitungstyp = new javax.swing.JLabel();
        lblLeitungQuerschnitt = new javax.swing.JLabel();
        cbxLeitungLeitungstyp = new javax.swing.JComboBox();
        cbxLeitungMaterial = new javax.swing.JComboBox();
        cbxLeitungQuerschnitt = new javax.swing.JComboBox();
        sprLeitung = new javax.swing.JSeparator();

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 13));                          // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/de/cismet/belis/resource/icon/22/leitung.png"))); // NOI18N
        jLabel1.setText("Leitung");                                                        // NOI18N

        lblLeitungMaterial.setText("Material:"); // NOI18N

        lblLeitungLeitungstyp.setText("Leitungstyp:"); // NOI18N

        lblLeitungQuerschnitt.setText("Querschnitt:"); // NOI18N

        cbxLeitungLeitungstyp.setEnabled(false);
        cbxLeitungLeitungstyp.setRenderer(new DefaultListCellRenderer() {

                @Override
                public Component getListCellRendererComponent(
                        final JList list,
                        final Object value,
                        final int index,
                        final boolean isSelected,
                        final boolean cellHasFocus) {
                    super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                    if (value == null) {
                        setText(comboBoxNullValue);
                    } else if (value instanceof de.cismet.cids.custom.beans.belis.LeitungstypCustomBean) {
                        final de.cismet.cids.custom.beans.belis.LeitungstypCustomBean lt =
                            (de.cismet.cids.custom.beans.belis.LeitungstypCustomBean)value;
                        setText(lt.getBezeichnung());
                    }
                    return this;
                }
            });

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${currentEntity.fk_leitungstyp}"),
                cbxLeitungLeitungstyp,
                org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        cbxLeitungMaterial.setEnabled(false);
        cbxLeitungMaterial.setRenderer(new DefaultListCellRenderer() {

                @Override
                public Component getListCellRendererComponent(
                        final JList list,
                        final Object value,
                        final int index,
                        final boolean isSelected,
                        final boolean cellHasFocus) {
                    super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                    if (value == null) {
                        setText(comboBoxNullValue);
                    } else if (value instanceof de.cismet.cids.custom.beans.belis.MaterialLeitungCustomBean) {
                        final de.cismet.cids.custom.beans.belis.MaterialLeitungCustomBean mt =
                            (de.cismet.cids.custom.beans.belis.MaterialLeitungCustomBean)value;
                        setText(mt.getBezeichnung());
                    }
                    return this;
                }
            });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${currentEntity.material}"),
                cbxLeitungMaterial,
                org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        cbxLeitungQuerschnitt.setEnabled(false);
        cbxLeitungQuerschnitt.setRenderer(new DefaultListCellRenderer() {

                @Override
                public Component getListCellRendererComponent(
                        final JList list,
                        final Object value,
                        final int index,
                        final boolean isSelected,
                        final boolean cellHasFocus) {
                    super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                    if (value == null) {
                        setText(comboBoxNullValue);
                    } else if (value instanceof de.cismet.cids.custom.beans.belis.QuerschnittCustomBean) {
                        final de.cismet.cids.custom.beans.belis.QuerschnittCustomBean qt =
                            (de.cismet.cids.custom.beans.belis.QuerschnittCustomBean)value;
                        if (qt.getGroesse() != null) {
                            setText(qt.getGroesse().toString());
                        } else {
                            setText("");
                        }
                    }
                    return this;
                }
            });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${currentEntity.querschnitt}"),
                cbxLeitungQuerschnitt,
                org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        final javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                        lblLeitungLeitungstyp).addComponent(lblLeitungMaterial).addComponent(lblLeitungQuerschnitt))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                        cbxLeitungQuerschnitt,
                        0,
                        250,
                        Short.MAX_VALUE).addComponent(cbxLeitungMaterial, 0, 156, Short.MAX_VALUE).addComponent(
                        cbxLeitungLeitungstyp,
                        javax.swing.GroupLayout.Alignment.TRAILING,
                        0,
                        156,
                        Short.MAX_VALUE)).addContainerGap()));
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(
                        lblLeitungLeitungstyp).addComponent(
                        cbxLeitungLeitungstyp,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        21,
                        javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(
                        lblLeitungMaterial).addComponent(
                        cbxLeitungMaterial,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        22,
                        javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(
                        lblLeitungQuerschnitt).addComponent(
                        cbxLeitungQuerschnitt,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        22,
                        javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(142, Short.MAX_VALUE)));

        jPanel2Layout.linkSize(
            javax.swing.SwingConstants.VERTICAL,
            new java.awt.Component[] { cbxLeitungLeitungstyp, cbxLeitungMaterial, cbxLeitungQuerschnitt });

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup().addContainerGap().addGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(
                        jPanel2,
                        javax.swing.GroupLayout.Alignment.LEADING,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE).addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                        sprLeitung,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        270,
                        Short.MAX_VALUE)).addContainerGap()));
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addContainerGap().addComponent(jLabel1).addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
                    sprLeitung,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    10,
                    javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
                    jPanel2,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE).addContainerGap()));

        bindingGroup.bind();
    } // </editor-fold>//GEN-END:initComponents

    @Override
    BindingGroup getBindingGroup() {
        return bindingGroup;
    }

    @Override
    void initPanel() {
        bindingGroup.addBindingListener(new PanelBindingListener());
        try {
            final Collection<MaterialLeitungCustomBean> material = CidsBroker.getInstance().getAllMaterialLeitung();
            createSortedCBoxModelFromCollection(material, cbxLeitungMaterial);
        } catch (ActionNotSuccessfulException ex) {
            cbxLeitungMaterial.setModel(new DefaultComboBoxModel());
        }
        cbxLeitungMaterial.setSelectedItem(null);

        try {
            leitungstypen = CidsBroker.getInstance().getAllLeitungstypen();
            createSortedCBoxModelFromCollection(leitungstypen, cbxLeitungLeitungstyp);
        } catch (ActionNotSuccessfulException ex) {
            cbxLeitungLeitungstyp.setModel(new DefaultComboBoxModel());
        }
        cbxLeitungLeitungstyp.setSelectedItem(null);

        try {
            final Collection<QuerschnittCustomBean> querschnitt = CidsBroker.getInstance().getAllQuerschnitte();
            createSortedCBoxModelFromCollection(querschnitt, cbxLeitungQuerschnitt);
        } catch (ActionNotSuccessfulException ex) {
            cbxLeitungQuerschnitt.setModel(new DefaultComboBoxModel());
        }
        cbxLeitungQuerschnitt.setSelectedItem(null);
    }

    @Override
    void initComponentToLabelMap() {
        componentToLabelMap.put(cbxLeitungLeitungstyp, lblLeitungLeitungstyp);
        componentToLabelMap.put(cbxLeitungMaterial, lblLeitungMaterial);
        componentToLabelMap.put(cbxLeitungQuerschnitt, lblLeitungQuerschnitt);
    }

    @Override
    public void setElementsNull() {
        // does nothing atm
    }

    @Override
    public void setPanelEditable(final boolean isEditable) {
        cbxLeitungLeitungstyp.setEnabled(isEditable);
        cbxLeitungMaterial.setEnabled(isEditable);
        cbxLeitungQuerschnitt.setEnabled(isEditable);
    }
}
