/*
 * AlreadyLockedObjectsPanel.java
 *
 * Created on 31. März 2009, 12:40
 */
package de.cismet.belis.panels;

import de.cismet.belisEE.entity.Lock;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Converter;

/**
 *
 * @author  spuhl
 */
public class AlreadyLockedObjectsPanel extends javax.swing.JPanel {

    private ArrayList<Lock> lockedObjects;
    BindingGroup bindingGroup2 = new BindingGroup();
    public static final String PROP_LOCKED_OBJECTS="lockedObjects";
    /** Creates new form AlreadyLockedObjectsPanel */
    public AlreadyLockedObjectsPanel(ArrayList<Lock> lockedObjects) {
        this.lockedObjects = lockedObjects;
        initComponents();                            
        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,this, org.jdesktop.beansbinding.ELProperty.create("${lockedObjects}"), jXTable1, org.jdesktop.beansbinding.ELProperty.create("${model}"));          
        binding.setConverter(new LockConverter());
        bindingGroup2.addBinding(binding);
        bindingGroup2.bind();
    }
    
    protected PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);

    /**
     * Add PropertyChangeListener.
     *
     * @param listener
     */
    public void addPropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.addPropertyChangeListener(listener);
    }

    /**
     * Remove PropertyChangeListener.
     *
     * @param listener
     */
    public void removePropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.removePropertyChangeListener(listener);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jXTable1);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/belis/resource/icon/48/error.png"))); // NOI18N

        jLabel2.setText("<html><table width=\"250\" border=\"0\"><tr><td>Es gibt bereis gesperrte Objekte. Bitte  veringern Sie Ihre Auswahl oder kontaktieren  Sie den entsprechenden Sachbearbeiter.</td></tr></table></html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    ((JDialog) this.getRootPane().getParent()).dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    public ArrayList<Lock> getLockedObjects() {
        return lockedObjects;
    }

    public void setLockedObjects(ArrayList<Lock> lockedObjects) {
        this.lockedObjects = lockedObjects;
        propertyChangeSupport.firePropertyChange(PROP_LOCKED_OBJECTS,null, lockedObjects);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTable jXTable1;
    // End of variables declaration//GEN-END:variables
}
class LockConverter extends Converter<ArrayList<Lock>,DefaultTableModel>{
    private ArrayList<Lock> lockedObjects;    
    
    @Override
    public DefaultTableModel convertForward(ArrayList<Lock> lockedObjects) {
        this.lockedObjects=lockedObjects;
        Object[][] rows = null;
        if(lockedObjects != null && lockedObjects.size() != 0){
            rows = new Object[lockedObjects.size()][2];
        } else {
            rows = new Object[0][2];
        }
        int row=0;
        for(Lock curLock:lockedObjects){
            rows[row][0]=curLock.getUserString();
            rows[row][1]=curLock.getTimestamp();
            row++;
        }                
        return new javax.swing.table.DefaultTableModel(
            rows,
            new String [] {
                "Benutzer", "Datum"
            }
        ){
            Class[] types = new Class [] {
                java.lang.String.class, Date.class
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
            
        };
    }

    @Override
    public ArrayList<Lock> convertReverse(DefaultTableModel arg0) {
        return lockedObjects;
    }
    
}

